blank_issues_enabled: false
contact_links:
  - name: Vonage Developer Community Slack
    url: https://developer.nexmo.com/community/slack
  - name: VonageDev on Twitter
    url: https://twitter.com/VonageDev