name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ dev ]
jobs:
  build:
    if: github.event.head_commit.committer.name != 'Versioning Action'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install dependencies
        run: |
          npm install
      - name: Build extension
        run: |
          npm run compile